<?php
/**
 * Central configuration + helpers.
 *
 * Settings are resolved in this order:
 *   1. Environment variables (e.g. GROQ_API_KEY, DB_HOST ...)
 *   2. api/settings.local.php   (written by the Settings page; gitignored)
 *   3. Hard defaults below
 *
 * settings.local.php is a PHP file that simply `return`s an array, so even
 * if it is requested directly in a browser it never leaks its contents.
 */

declare(strict_types=1);

define('SETTINGS_FILE', __DIR__ . '/settings.local.php');

define('GROQ_URL', 'https://api.groq.com/openai/v1/chat/completions');
define('DEFAULT_MODEL', 'llama-3.3-70b-versatile');
define('MAX_ROWS', 50);

/** Default values for every known setting key. */
function default_settings(): array
{
    return [
        'groq_api_key' => '',
        'groq_model'   => DEFAULT_MODEL,
        'db_host'      => '127.0.0.1',
        'db_port'      => '3306',
        'db_name'      => 'pallaw',
        'db_user'      => 'root',
        'db_pass'      => '',
    ];
}

/** Load locally-saved settings (from settings.local.php). */
function load_local_settings(): array
{
    if (is_file(SETTINGS_FILE)) {
        $data = include SETTINGS_FILE;
        if (is_array($data)) {
            return $data;
        }
    }
    return [];
}

/**
 * Resolve a single setting (env > local file > default).
 */
function setting(string $key, $fallback = null)
{
    static $local = null;
    if ($local === null) {
        $local = load_local_settings();
    }

    $env = getenv(strtoupper($key));
    if ($env !== false && $env !== '') {
        return $env;
    }
    if (array_key_exists($key, $local) && $local[$key] !== '') {
        return $local[$key];
    }
    $defaults = default_settings();
    return $defaults[$key] ?? $fallback;
}

/** Persist settings to settings.local.php. Returns true on success. */
function save_settings(array $values): bool
{
    $allowed = array_keys(default_settings());
    $clean   = [];
    foreach ($allowed as $k) {
        if (array_key_exists($k, $values)) {
            $clean[$k] = (string) $values[$k];
        }
    }
    // Merge with whatever is already saved so a partial update doesn't wipe keys.
    $merged = array_merge(load_local_settings(), $clean);

    $php = "<?php\n// Auto-generated by the Settings page. Do not commit.\nreturn "
        . var_export($merged, true) . ";\n";

    return @file_put_contents(SETTINGS_FILE, $php) !== false;
}

/** Send a JSON response and stop. */
function json_response(int $status, array $payload): void
{
    http_response_code($status);
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    exit;
}

/** Read and decode a JSON request body. */
function read_json_body(): array
{
    $raw = file_get_contents('php://input');
    if ($raw === false || $raw === '') {
        return [];
    }
    $data = json_decode($raw, true);
    return is_array($data) ? $data : [];
}
