<?php
/**
 * Central configuration + helpers.
 *
 * ┌──────────────────────────────────────────────────────────────┐
 * │  EDIT YOUR DATABASE + ADMIN LOGIN BELOW (or set env vars).      │
 * │  The Groq API key/model are managed from the Settings page.    │
 * └──────────────────────────────────────────────────────────────┘
 */

declare(strict_types=1);

/* =====================================================================
   1) DATABASE  — configured here (NOT in the admin Settings page)
   ===================================================================== */
define('DB_HOST', getenv('DB_HOST') ?: '127.0.0.1');
define('DB_PORT', getenv('DB_PORT') ?: '3306');
define('DB_NAME', getenv('DB_NAME') ?: 'pallaw');
define('DB_USER', getenv('DB_USER') ?: 'root');
define('DB_PASS', getenv('DB_PASS') ?: '');

/* =====================================================================
   2) ADMIN LOGIN  — the lock for the whole panel.
      CHANGE THESE before deploying (or set ADMIN_USERNAME / ADMIN_PASSWORD
      environment variables, which always take priority).
   ===================================================================== */
define('ADMIN_USERNAME', getenv('ADMIN_USERNAME') ?: 'admin');
define('ADMIN_PASSWORD', getenv('ADMIN_PASSWORD') ?: 'pallaw@admin');

/* =====================================================================
   3) GROQ  — key & model are saved from the Settings page
      (api/settings.local.php, gitignored) or via env vars.
   ===================================================================== */
define('GROQ_URL', 'https://api.groq.com/openai/v1/chat/completions');
define('DEFAULT_MODEL', 'llama-3.3-70b-versatile');
define('MAX_ROWS', 100);

define('SETTINGS_FILE', __DIR__ . '/settings.local.php');

/** Default values for Groq settings managed by the UI. */
function default_settings(): array
{
    return [
        'groq_api_key' => '',
        'groq_model'   => DEFAULT_MODEL,
    ];
}

/** Load locally-saved settings (from settings.local.php). */
function load_local_settings(): array
{
    if (is_file(SETTINGS_FILE)) {
        $data = include SETTINGS_FILE;
        if (is_array($data)) {
            return $data;
        }
    }
    return [];
}

/** Resolve a Groq setting (env > local file > default). */
function setting(string $key, $fallback = null)
{
    static $local = null;
    if ($local === null) {
        $local = load_local_settings();
    }
    $env = getenv(strtoupper($key));
    if ($env !== false && $env !== '') {
        return $env;
    }
    if (array_key_exists($key, $local) && $local[$key] !== '') {
        return $local[$key];
    }
    $defaults = default_settings();
    return $defaults[$key] ?? $fallback;
}

/** Persist Groq settings to settings.local.php. */
function save_settings(array $values): bool
{
    $allowed = array_keys(default_settings());
    $clean   = [];
    foreach ($allowed as $k) {
        if (array_key_exists($k, $values)) {
            $clean[$k] = (string) $values[$k];
        }
    }
    $merged = array_merge(load_local_settings(), $clean);
    $php = "<?php\n// Auto-generated by the Settings page. Do not commit.\nreturn "
        . var_export($merged, true) . ";\n";
    return @file_put_contents(SETTINGS_FILE, $php) !== false;
}

/** Send a JSON response and stop. */
function json_response(int $status, array $payload): void
{
    http_response_code($status);
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    exit;
}

/** Read and decode a JSON request body. */
function read_json_body(): array
{
    $raw = file_get_contents('php://input');
    if ($raw === false || $raw === '') {
        return [];
    }
    $data = json_decode($raw, true);
    return is_array($data) ? $data : [];
}
